# Generated by Django 5.0.2 on 2024-03-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sevenshadesapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maincategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='MySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoryname', models.CharField(default='', max_length=70)),
                ('icon', models.ImageField(upload_to='static/')),
                ('maincategoryid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
            ],
        ),
    ]
