# Generated by Django 5.0.2 on 2024-03-29 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=150)),
                ('icon', models.ImageField(upload_to='static/')),
                ('brandid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.brands')),
                ('maincategoryid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.maincategory')),
                ('mysubcategoryid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.mysubcategory')),
            ],
        ),
    ]
