# Generated by Django 5.0.2 on 2024-03-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0003_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='mysubcategoryid',
            new_name='subcategoryid',
        ),
    ]
