# Generated by Django 5.0.2 on 2024-04-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0005_productdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productdetails',
            old_name='productdid',
            new_name='productid',
        ),
    ]
