# Generated by Django 5.0.2 on 2024-04-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0007_alter_productdetails_offerprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='offerprice',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='qty',
            field=models.IntegerField(default=''),
        ),
    ]
