# Generated by Django 5.0.2 on 2024-04-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0011_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='pictures',
        ),
        migrations.AddField(
            model_name='banner',
            name='icon',
            field=models.TextField(default=''),
        ),
    ]
