# Generated by Django 5.0.2 on 2024-07-02 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sevenshadesapp', '0013_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AddField(
            model_name='signup',
            name='mobileno',
            field=models.CharField(default='', max_length=15, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='signup',
            name='emailid',
            field=models.CharField(default='', max_length=70, unique=True),
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=70)),
                ('address', models.CharField(default='', max_length=70)),
                ('city', models.CharField(default='', max_length=70)),
                ('postcode', models.CharField(default='', max_length=70)),
                ('mobileno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sevenshadesapp.signup')),
            ],
        ),
    ]
